name: Enterprise Core CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3
      
    - name: Set up Java Engine
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    # We tell the robot to change directory into 'wallet' before compiling
    - name: Compile Application
      run: ./mvnw clean package -DskipTests
      working-directory: wallet
      
    # We also tell Docker to look inside the 'wallet' folder for the Dockerfile
    - name: Build Docker Container
      run: docker build -t fintech-core-engine:latest .
      working-directory: wallet
